### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by LuckiestMan** [Richou/react-native-android-location-enabler#2]
Hello,

I just added your plugin into my project, but i can't compile it

`/Users/mad/Documents/HangoverApp/node_modules/react-native-android-location-enabler/android/src/main/java/com/heanoria/library/reactnative/locationenabler/RNAndroidLocationEnablerModule.java:36: error: RNAndroidLocationEnablerModule is not abstract and does not override abstract method onNewIntent(Intent) in ActivityEventListener
public class RNAndroidLocationEnablerModule extends ReactContextBaseJavaModule implements GoogleApiClient.ConnectionCallbacks, GoogleApiClient.OnConnectionFailedListener, ResultCallback<LocationSettingsResult>, ActivityEventListener {
       ^
/Users/mad/Documents/HangoverApp/node_modules/react-native-android-location-enabler/android/src/main/java/com/heanoria/library/reactnative/locationenabler/RNAndroidLocationEnablerModule.java:122: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors`

it's on ResultCallback<LocationSettingsResult> and the Override of onActivityResult()

I used react-native link, but checked the code with your manual setup's step and it's the same...

(I use the i18n plugin, fbsdk plugin too, maybe it's doing a conflict, don't know)

android sdk 25

Thank you in advance

**Comment by LuckiestMan** [comment]
Resolved, using the 1.0.2 now it's working

**Comment by Richou** [comment]
Ok, but it still not normal, I will check it as soon as possible, thx for your issue.

**Comment by Keksike** [comment]
I'm experiencing same problem, my react/react-native versions:
```
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.0",
```

**Comment by Richou** [comment]
Yes sorry for that, I still did not check that.
Did you try to use the version 1.0.2 ?

**Comment by Richou** [comment]
I published a new release version 1.0.4, can you test and tell me if that corrected your issue ? 
Thx.

**Comment by jamesalways** [comment]
@Richou Hi! Same problem. 1.0.4 didn't resolve it. With 1.0,2 works! Please fix it in newer versions!

Thanks!!!

**Comment by urska19** [comment]
Hi.

I installed the latest version` 1.0.4` using `react-native 0.44.0` and got following error :
```
.../node_modules/react-native-android-location-enabler/android/src/main/java/com/heanoria/library/reactnative/locationenabler/RNAndroidLocationEnablerPackage.java:13: error: RNAndroidLocationEnablerPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNAndroidLocationEnablerPackage implements ReactPackage {
       ^
1 error
```

If I understand correctly in the newest version of react `0.47.`,  method `createJSModules() `[was removed](https://github.com/facebook/react-native/releases/tag/v0.47.2), which I guess is now an issue for older versions of react-native, when installing version ` 1.0.4` of this package.

[Fix](https://github.com/react-native-community/react-native-svg/pull/414), that worked for me, was to add following in `RNAndroidLocationEnablerPackage.java`
```
     @Override
     public List<Class<? extends JavaScriptModule>> createJSModules() {
       return Collections.emptyList();
     }
```

**Comment by Richou** [comment]
I released a new version 1.0.5, please tell me if that fixed your issue. thx.

**Comment by akshita-2505** [comment]
![Screenshot 2021-05-04 at 3 04 43 PM](https://user-images.githubusercontent.com/45819519/116985466-218ac780-acea-11eb-969c-19eb55eaad51.png)


version: 1.2.2
Facing this issue, Please look into this
@Richou
